### ISSUE TITLE
Exclude some windows from the list

### ISSUE THREAD

**Issue by DavidEGx** [TC72/telescope-tele-tabby.nvim#2]
o/ Thanks for the plugin. I think it'd be superb to be able to exclude some windows from the tablist. Thinking mainly of windows that belong to some plugins like nerdtree, nvim-tree, tagbar, vista, etc.

Example with only 2 tabs opened ("tab1" and "tab2"):
```
  2 4a      vX/__Tagbar__.2                                              
  2 3a      vX/tabe tab2                                                 
  2 2a      vX//tmp/.mount_nvim5WoZ9s/usr/share/nvim/runtime/doc/help.txt
  2 1a      vX/NERD_tree_2                                               
  1 3a      vX/__Tagbar__.1                                              
  1 2a      vX/tab1                                                      
> 1 1a      vX/NERD_tree_1                                               
```

"*NERD_tree_*" and "*Tagbar*" is only noise from my point of view. Never want to jump there.

**Comment by TC72** [comment]
I'm now checking the `buftype` of the buffer in each window. If the `buftype` is not a normal file, which is shown by an empty `buftype`, then I don't include it in the list.  
This automatically handles the nerd tree and tagbar examples you've shown.

If this is excluding windows people would like to see in the list then I'll look at a different way of filtering, but this was a simple fix to cover the issues I've seen.

**Comment by DavidEGx** [comment]
Looks good, thanks!.
